=encoding utf8

=head1 はじめに

これは僕の小説をただアップするリポジトリです。

=head1 著作権

この小説は クリエイティブ・コモンズ 表示 - 非営利 - 継承 2.1 日本 ライセンスの下に提供されています。

http://creativecommons.org/licenses/by-nc-sa/2.1/jp/

=head1 コンパイル環境

もし、僕の小説をコンパイルしたいという方は、次のものが必要です。

=over

=item LaTeX

=item OMake

=back

これらをインストールして、omakeコマンドでコンパイル出来るはずです。

=head1 ダウンロード

コンパイル環境が無い方は、以下のURLからPDFを入手出来ます。

http://db.tt/X2mxocwn

=head1 問い合せ

この内容に関する質問・感想・ミス報告については、
issueかプルリクエストでやっていただけるとすごくありがたいです。

とりあえず、@yoshimura_yuu にリプライやDMを飛ばしていただければ、
なんとかします。

=head1 使い方

chapter[数字]というディレクトリの中にある、
[数字].texというファイルを自動的に結合してPDFを生産します。

[数字].texの[数字]の部分はセクション（section）です。

例えば、chapter2/2.texとは

 \chapter{}
 ......
 \chapter{}
     \section{}
     .......
	 \section{}
	 ここ！
 ......

の部分を指すことになります。

ファイルを新たに追加した場合や、
コンパイルが妙な場合は何回かomakeしてあげればだいたいなんとかなります。
