=encoding utf8

=head1 はじめに

これは僕の小説をただアップするリポジトリです。

=head1 コンパイル環境

もし、僕の小説をコンパイルしたいという方は、次のものが必要です。

=over

=item LaTeX

=item OMake

=back

これらをインストールして、omakeコマンドでコンパイル出来るはずです。

=head1 使い方

=head2 概要

chapter[数字]というディレクトリの中にある、
[数字].texというファイルを自動的に結合してPDFを生産します。

=head2 構造

[数字].texの[数字]の部分はセクション（section）です。

例えば、chapter2/2.texとは

 \chapter{}
 ......
 \chapter{}
     \section{}
     .......
	 \section{}
	 ここ！
 ......

の部分を指すことになります。

なので人間がやる主な作業は、
chapter[数字]/[数字].texの中身をひたすら編集することです。

=head2 ファイルの意味

=over

=item main.tex

これは表紙部分です。タイトルや作者情報を記述します。
このファイルはOMakeによってB<編集されません>。

main.texはbody.texを読み込んでいます。

=item body.tex

これは、chapter[数字]/[数字].texを読み込むファイルです。

 \chapter{}
 \section{}
 \input{chapter1/1.tex}
 \clearpage
 \section{}
 \input{chapter1/2.tex}
 \clearpage

このように、inputでひたすら読み込んでゆきます。

このファイルはOMakeによってB<編集されます>。
しかし、ファイルが存在しないとエラーになるので、
空ファイルでも良いので置いてください。

=item OMakeroot

OMakeのコアとなる関数群をまとめたファイルです。

=item OMakefile

設定兼、OMakerootで定義した関数を実行する部分です。

TeXの設定や、セクションを格納するディレクトリ名（デフォルトではchapter[数字]）
を管理しています。

紙の大きさを調整したい時などは、編集の必要があります。

=item ./chapter[数字]/

セクション群を格納するディレクトリです。
この中に1.texや2.texなどを生産します。

この中にOMakefileを置く必要はB<ありません>。

=back

ファイルを新たに追加した場合や、
コンパイルが妙な場合は何回かomakeしてあげればだいたいなんとかなります。

=head1 問い合せ

この内容に関する質問・感想・ミス報告については、
issueかプルリクエストでやっていただけるとすごくありがたいです。

とりあえず、@yoshimura_yuu にリプライやDMを飛ばしていただければ、
なんとかします。


