=encoding utf8

=head1 はじめに

これは僕の小説をただアップするリポジトリです。

=head1 コンパイル環境

もし、僕の小説をコンパイルしたいという方は、次のものが必要です。

=over

=item LaTeX

=item OMake

=back

これらをインストールして、omakeコマンドでコンパイル出来るはずです。

=head1 使い方

chapter[数字]というディレクトリの中にある、
[数字].texというファイルを自動的に結合してPDFを生産します。

[数字].texの[数字]の部分はセクション（section）です。

例えば、chapter2/2.texとは

 \chapter{}
 ......
 \chapter{}
     \section{}
     .......
	 \section{}
	 ここ！
 ......

の部分を指すことになります。

ファイルを新たに追加した場合や、
コンパイルが妙な場合は何回かomakeしてあげればだいたいなんとかなります。

=head1 問い合せ

この内容に関する質問・感想・ミス報告については、
issueかプルリクエストでやっていただけるとすごくありがたいです。

とりあえず、@yoshimura_yuu にリプライやDMを飛ばしていただければ、
なんとかします。


